name: vb1980 4.4 build

on: 
#  push:
#    branches:
#    - "*"
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: 'Please select the model to compile'
        options:
        - 'B70'
        - 'BELL-A040WQ'
        - 'CR660x'
        - 'DIR-878'
        - 'DIR-882'
        - 'EA7500'
        - 'E8820V2'
        - 'GHL'
        - 'JCG-836PRO'
        - 'JCG-AC860M'
        - 'JCG-Q20-PB'
        - 'JCG-Q20'
        - 'JCG-Y2'
        - 'K2P-USB'
        - 'K2P-NANO'
        - 'K2P'
        - 'MI-4'
        - 'MI-R3G'
        - 'MI-R3P-PB'
        - 'MI-R3P-SPI'
        - 'MI-R3P'
        - 'MI-R4A'
        - 'MR2600'
        - 'MSG1500'
        - 'MSG1500-Z'
        - 'NETGEAR-BZV'
        - 'NEWIFI'
        - 'NEWIFI3'
        - 'QM-B1'
        - 'R2100'
        - 'R6800'
        - 'RE-CP-02'
        - 'RM2100'
        - 'RT-AC85P'
        - 'TX1801'
        - 'WR1200JS'
        - 'XY-C1'
        - 'ZTE-E8820S'
        - 'WE410443-TC'
        default: 'K2P'

env:
  REPO_URL: https://github.com/vb1980/padavan-4.4.git
  REPO_BRANCH: main
  TNAME: WR1200JS
  DEPENDS_FILE: depends.txt
  SETTING_SCRIPT: mt7621/vb1980_4.4_settings.sh
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: false
  
jobs:
  build:
    name: ${{ inputs.target }}
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: hendrikmuhs/ccache-action@v1.2.3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.2'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-v1
          restore-keys: |
            ${{ runner.os }}-go-
            
      - name: Prepare environment
        run: |
          sudo apt update
          sudo apt install libtool-bin gperf python3-docutils autopoint gettext ccache
          
          export BUILD_DATE=$(TZ=UTC-8 date +"%y.%m.%d_%H.%M.%S")
          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
          SOURCE_REPO="$(echo $REPO_URL | awk -F '/' '{print $(NF)}')"
          echo "SOURCE_REPO=$SOURCE_REPO" >> $GITHUB_ENV
          
      - name: Clone source code
        run: |
          git clone --depth=1 --branch $REPO_BRANCH $REPO_URL rt-n56u
          cd rt-n56u
          echo "======================="
          lscpu | egrep "name|Core|Thread"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1
          echo "======================="
        
      - name: Load configuration
        run: |
          set -x
          chmod +x $SETTING_SCRIPT
          cd rt-n56u/trunk/configs/templates
          cp -f ${{ inputs.target }}.config .config
          $GITHUB_WORKSPACE/$SETTING_SCRIPT
          cp -f .config ${{ inputs.target }}.config
        
      - name: Start Build
        run: |
          make ${{ inputs.target }}
          echo "TAG_ANME=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Upload firmware
        uses: actions/upload-artifact@main
        if: env.UPLOAD_FIRMWARE == 'true'
        with:
          name: ${{ inputs.target }}-${{ env.TAG_ANME }}
          path: rt-n56u/trunk/images/*.trx

      - name: Release Firmware
        uses: softprops/action-gh-release@master
        if: env.UPLOAD_RELEASE == 'true'
        with:
          tag_name: ${{env.SOURCE_REPO}}_${{ env.REPO_BRANCH }}_${{env.BUILD_DATE}}
          files: rt-n56u/trunk/images/*.trx
          body: |
              Padavan固件包。
