name: vb1980 4.4 build

on: 
#  push:
#    branches:
#    - "*"
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: 'Please select the model to compile'
        options:
        - 'K2P'
        - 'NEWIFI3'
        - 'RM2100'
        - 'WR1200JS'
        - 'XY-C1'

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  REPO_URL: https://github.com/weijiefu1673/vb1980_padavan-4.4.git
  REPO_BRANCH: main
  TNAME: WR1200JS
  DEPENDS_FILE: depends.txt
  SETTING_SCRIPT: config/vb1980_4.4_settings.sh
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: false
  
jobs:
  build:
    name: ${{ inputs.target }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@main
      
      - uses: hendrikmuhs/ccache-action@main
        with:
          key: vb1980_4.4_${{ inputs.target }}

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          check-latest: true
          
      - uses: actions/setup-go@main
        with:
          go-version: '^1.19.2'
          
      - uses: actions/cache@main
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-v1
          restore-keys: |
            ${{ runner.os }}-go-
    
      - name: Prepare environment
        run: |
          sudo -E apt-get update
          sudo -E apt-get install libtool-bin gperf python3-docutils autopoint gettext ccache
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get -y clean
          sudo -E timedatectl set-timezone "Asia/Shanghai"
          
          export BUILD_DATE=$(TZ=UTC-8 date +"%y.%m.%d_%H.%M.%S")
          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
          SOURCE_REPO="$(echo $REPO_URL | awk -F '/' '{print $(NF)}')"
          echo "SOURCE_REPO=$SOURCE_REPO" >> $GITHUB_ENV
          
      - name: Clone source code
        run: |
          git clone --depth=1 --branch $REPO_BRANCH $REPO_URL rt-n56u
          cd rt-n56u
          echo "======================="
          lscpu | egrep "name|Core|Thread"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1
          echo "======================="
        
      - name: Load configuration
        run: |
          set -x
          chmod +x $SETTING_SCRIPT
          cd rt-n56u/trunk
          $GITHUB_WORKSPACE/$SETTING_SCRIPT ${{ inputs.target }}
        
      - name: Compile the firmware
        run: |
          cd rt-n56u
          sed -i 's/tsl0922\/padavan/weijiefu1673\/vb1980_padavan-4.4/g' Makefile
          make ${{ inputs.target }}

      - name: Upload firmware
        uses: actions/upload-artifact@main
        if: env.UPLOAD_FIRMWARE == 'true'
        with:
          name: Padavan_firmware_${{ inputs.target }}_${{ env.BUILD_DATE }}
          path: |
            rt-n56u/trunk/images/*.trx
            rt-n56u/trunk/.config

      - name: Release Firmware
        uses: softprops/action-gh-release@master
        if: env.UPLOAD_RELEASE == 'true'
        with:
          tag_name: ${{env.SOURCE_REPO}}_${{ env.REPO_BRANCH }}_${{ inputs.target }}_${{env.BUILD_DATE}}
          files: |
            rt-n56u/trunk/images/*.trx
            rt-n56u/trunk/.config
          body: |
              Padavan固件包。
